export const SERVER_CONNECTING = 'SERVER_CONNECTING';
export const SERVER_CONNECTED = 'SERVER_CONNECTED';

export const SERVER_DISCONNECTING = 'SERVER_DISCONNECTING';
export const SERVER_DISCONNECTED = 'SERVER_DISCONNECTED';

export const LOGIN_SUCEEDED = 'LOGIN_SUCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SOMEONE_ENTERED = 'SOMEONE_ENTERED';
export const SOMEONE_LEFT = 'SOMEONE_LEFT';

export const SOMEONE_RENAMED = 'SOMEONE_RENAMED';

export const CLIENTS_ARRIVED = 'CLIENTS_ARRIVED';

export const ENTER_ROOM = 'ENTER_ROOM';

export const SEND_TEXT = 'SEND_TEXT';
export const RECEIVE_TEXT = 'RECEIVE_TEXT';
